table AI&PD
	lineageTag: a678d1c6-a42c-4432-8736-b6e91c377641

	measure 'Total Oppts AI & PD' = CALCULATE([Total Projects],'PreSales Tracker'[Stream (Short)]="App Innovation")
		formatString: 0
		lineageTag: a25de2b6-e2a1-4bd3-8113-9b0e2321cba1

	measure 'Won Deals AI & PD' = CALCULATE([Won Deals],'PreSales Tracker'[Stream (Short)]="App Innovation")
		formatString: 0
		lineageTag: 191706a9-4d0d-4442-aa0e-0fa87e9cbb3c

	measure 'In progress AI & PD' = CALCULATE([In Progress Deals],'PreSales Tracker'[Stream (Short)]="App Innovation")
		formatString: 0
		lineageTag: 5ab5ec50-4fbf-4510-bce5-90e4d8e42b2d

	measure 'Lost Deals AI & PD' = CALCULATE([Lost Deals],'PreSales Tracker'[Stream (Short)]="App Innovation")
		formatString: 0
		lineageTag: cc7b60dd-c930-46cf-9408-4e2e6d121483

	partition AI&PD = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

