table CI
	lineageTag: 33d2b51d-9677-43c2-97a5-7d191caf13ef

	measure 'Total Oppts CI' = CALCULATE([Total Projects],'PreSales Tracker'[Stream (Short)]="Cloud Implementation")
		formatString: 0
		lineageTag: 67eaa946-1057-44f3-80d3-ad6a37e2f616

	measure 'In progress CI' =
			
			var inprogress=CALCULATE([In Progress Deals],'PreSales Tracker'[Stream (Short)]="Cloud Implementation")
			RETURN
			IF(inprogress=BLANK(),0,inprogress)
		formatString: 0
		lineageTag: ea63d814-5c5f-4f56-9781-9acaa12de3b3

	measure 'Measure 7'
		lineageTag: 0c584cb4-4313-4768-bd51-b55aa7604472

	measure 'Won Deals CI' = CALCULATE([Won Deals],'PreSales Tracker'[Stream (Short)]="Cloud Implementation")
		formatString: 0
		lineageTag: 6c40d998-fb09-4630-928b-670c754151b9

	measure 'Lost Deals CI' =
			
			var lost=CALCULATE([Lost Deals],'PreSales Tracker'[Stream (Short)]="Cloud Implementation")
			RETURN
			if(lost=BLANK(),0,lost)
		formatString: 0
		lineageTag: 7f0e10e7-1042-43ba-af7e-a7e7a0b30417

	partition CI = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

