table HR_Analytics
	lineageTag: c1dcd20b-f2b1-4474-8d23-5d939f2b90b9

	measure 'Total Employees' = DISTINCTCOUNT(HR_Analytics[EmployeeNumber])
		formatString: 0
		lineageTag: 9b062bdd-1566-47b6-ba41-6a88c3bb2e91

	measure 'Attrition Rate' = CALCULATE(COUNT(HR_Analytics[Attrition]),HR_Analytics[Attrition]="Yes")
		formatString: 0
		lineageTag: b15d7034-a8b6-449c-943d-07497752e9f3

	measure 'Attrition Rate%' = DIVIDE([Attrition Rate],[Total Employees])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6616099e-84ff-4138-97e2-84e9faaab54d

	measure 'Male Count' = CALCULATE([Total Employees],HR_Analytics[Gender]="Male")
		formatString: 0
		lineageTag: c7c27e1c-94d1-4134-a205-9a5e317f2301

	measure 'Female Count' = CALCULATE([Total Employees],HR_Analytics[Gender]="Female")
		formatString: 0
		lineageTag: 935b732c-a4b1-4ae3-9969-5559053f7510

	column EmpID
		dataType: string
		lineageTag: bb7705ea-cdd1-4846-b3e4-463a470c2410
		summarizeBy: none
		sourceColumn: EmpID

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 7929d66b-bfa9-4654-8569-1853ecef2245
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column AgeGroup
		dataType: string
		lineageTag: a1f37b1c-8fdd-4b6b-80a7-93456673393b
		summarizeBy: none
		sourceColumn: AgeGroup

		annotation SummarizationSetBy = Automatic

	column Attrition
		dataType: string
		lineageTag: 40add968-07d7-4b8f-a2db-c1715dec6017
		summarizeBy: none
		sourceColumn: Attrition

		annotation SummarizationSetBy = Automatic

	column BusinessTravel
		dataType: string
		lineageTag: 77d921d7-8ae3-4767-921c-989361a67a8c
		summarizeBy: none
		sourceColumn: BusinessTravel

		annotation SummarizationSetBy = Automatic

	column DailyRate
		dataType: int64
		formatString: 0
		lineageTag: d1eced0d-17b4-4f38-b361-eacf23e11e87
		summarizeBy: sum
		sourceColumn: DailyRate

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 23d02f53-8532-4960-bedd-770851f0951e
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column DistanceFromHome
		dataType: int64
		formatString: 0
		lineageTag: 52e64bc2-0d8f-4207-94a0-227fc55f1188
		summarizeBy: sum
		sourceColumn: DistanceFromHome

		annotation SummarizationSetBy = Automatic

	column Education
		dataType: int64
		formatString: 0
		lineageTag: f95f37d6-663b-49e8-b280-4335f381db81
		summarizeBy: sum
		sourceColumn: Education

		annotation SummarizationSetBy = Automatic

	column EducationField
		dataType: string
		lineageTag: 89bfaa5d-3163-4573-ad9d-888fe20b66cc
		summarizeBy: none
		sourceColumn: EducationField

		annotation SummarizationSetBy = Automatic

	column EmployeeCount
		dataType: int64
		formatString: 0
		lineageTag: f7774c07-8bf9-403e-9bf3-9e26602d141f
		summarizeBy: sum
		sourceColumn: EmployeeCount

		annotation SummarizationSetBy = Automatic

	column EmployeeNumber
		dataType: int64
		formatString: 0
		lineageTag: e926ee3b-ffc4-415c-9727-6b9900923c8f
		summarizeBy: sum
		sourceColumn: EmployeeNumber

		annotation SummarizationSetBy = Automatic

	column EnvironmentSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: 1a029ad1-09b2-4a62-8cc9-c84e33d97cde
		summarizeBy: sum
		sourceColumn: EnvironmentSatisfaction

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: b3029773-e4ae-4d65-9d1c-c15cfc17ac4a
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column HourlyRate
		dataType: int64
		formatString: 0
		lineageTag: cd5ba340-124b-4ab5-9a91-ca760d3a735b
		summarizeBy: sum
		sourceColumn: HourlyRate

		annotation SummarizationSetBy = Automatic

	column JobInvolvement
		dataType: int64
		formatString: 0
		lineageTag: 21104ab3-553b-4769-bdea-af8d567dd6af
		summarizeBy: sum
		sourceColumn: JobInvolvement

		annotation SummarizationSetBy = Automatic

	column JobLevel
		dataType: int64
		formatString: 0
		lineageTag: 4e934cc0-5770-461e-bf6d-e26ca7de0a14
		summarizeBy: sum
		sourceColumn: JobLevel

		annotation SummarizationSetBy = Automatic

	column JobRole
		dataType: string
		lineageTag: 4b722fa5-fb5b-4e46-b048-c82dee114c0c
		summarizeBy: none
		sourceColumn: JobRole

		annotation SummarizationSetBy = Automatic

	column JobSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: 4d3ab573-fe82-40e4-94d7-57d9a65021ce
		summarizeBy: sum
		sourceColumn: JobSatisfaction

		annotation SummarizationSetBy = Automatic

	column MaritalStatus
		dataType: string
		lineageTag: 6a94f523-babd-4698-9994-f7a252ab1dc4
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column MonthlyIncome
		dataType: int64
		formatString: 0
		lineageTag: 284a42f7-6d28-4dbc-a17f-574cf8e92120
		summarizeBy: sum
		sourceColumn: MonthlyIncome

		annotation SummarizationSetBy = Automatic

	column SalarySlab
		dataType: string
		lineageTag: 75b59dcd-a2ad-4a3a-bad2-d2310222798b
		summarizeBy: none
		sourceColumn: SalarySlab

		annotation SummarizationSetBy = Automatic

	column MonthlyRate
		dataType: int64
		formatString: 0
		lineageTag: 72c513db-4276-4964-b398-63e72ea39e87
		summarizeBy: sum
		sourceColumn: MonthlyRate

		annotation SummarizationSetBy = Automatic

	column NumCompaniesWorked
		dataType: int64
		formatString: 0
		lineageTag: 3ac4df7d-4cf3-4165-ba8f-c4047b8688f2
		summarizeBy: sum
		sourceColumn: NumCompaniesWorked

		annotation SummarizationSetBy = Automatic

	column Over18
		dataType: string
		lineageTag: 93a995ab-dd93-4dc4-bacc-7efb2bb165f1
		summarizeBy: none
		sourceColumn: Over18

		annotation SummarizationSetBy = Automatic

	column OverTime
		dataType: string
		lineageTag: 36593eb0-33b2-493a-b8eb-5bbbdf3d4bba
		summarizeBy: none
		sourceColumn: OverTime

		annotation SummarizationSetBy = Automatic

	column PercentSalaryHike
		dataType: int64
		formatString: 0
		lineageTag: 0ee77104-9f10-44b0-8e02-454463a47a70
		summarizeBy: sum
		sourceColumn: PercentSalaryHike

		annotation SummarizationSetBy = Automatic

	column PerformanceRating
		dataType: int64
		formatString: 0
		lineageTag: e289becc-2fa1-4c29-bcac-b7b76390d3f3
		summarizeBy: sum
		sourceColumn: PerformanceRating

		annotation SummarizationSetBy = Automatic

	column RelationshipSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: 68cdd675-2247-457a-b018-64f84a43d7cb
		summarizeBy: sum
		sourceColumn: RelationshipSatisfaction

		annotation SummarizationSetBy = Automatic

	column StandardHours
		dataType: int64
		formatString: 0
		lineageTag: ebe7d3f3-1c68-4f38-97c9-5059a18a4781
		summarizeBy: sum
		sourceColumn: StandardHours

		annotation SummarizationSetBy = Automatic

	column StockOptionLevel
		dataType: int64
		formatString: 0
		lineageTag: d9016217-1a4a-472a-9e5c-4433088c7eb5
		summarizeBy: sum
		sourceColumn: StockOptionLevel

		annotation SummarizationSetBy = Automatic

	column TotalWorkingYears
		dataType: int64
		formatString: 0
		lineageTag: 9d6edb4c-8e75-4fc7-9bad-b3b5d97e95a2
		summarizeBy: sum
		sourceColumn: TotalWorkingYears

		annotation SummarizationSetBy = Automatic

	column TrainingTimesLastYear
		dataType: int64
		formatString: 0
		lineageTag: 47f21e64-dae4-4a8b-9fab-5ed19ea22cf2
		summarizeBy: sum
		sourceColumn: TrainingTimesLastYear

		annotation SummarizationSetBy = Automatic

	column WorkLifeBalance
		dataType: int64
		formatString: 0
		lineageTag: 5394b48f-28f3-469a-96ac-47cc4b362477
		summarizeBy: sum
		sourceColumn: WorkLifeBalance

		annotation SummarizationSetBy = Automatic

	column YearsAtCompany
		dataType: int64
		formatString: 0
		lineageTag: 3b5a8178-323a-4cc9-995a-6310edb6bf74
		summarizeBy: sum
		sourceColumn: YearsAtCompany

		annotation SummarizationSetBy = Automatic

	column YearsInCurrentRole
		dataType: int64
		formatString: 0
		lineageTag: 5d7ebf4c-50eb-47e2-a25d-97273c8a0d37
		summarizeBy: sum
		sourceColumn: YearsInCurrentRole

		annotation SummarizationSetBy = Automatic

	column YearsSinceLastPromotion
		dataType: int64
		formatString: 0
		lineageTag: 9b27b186-655f-468b-a867-e73bc04d0df0
		summarizeBy: sum
		sourceColumn: YearsSinceLastPromotion

		annotation SummarizationSetBy = Automatic

	column YearsWithCurrManager
		dataType: int64
		formatString: 0
		lineageTag: 031e6850-ffd8-488d-9e1e-a19e912cf882
		summarizeBy: sum
		sourceColumn: YearsWithCurrManager

		annotation SummarizationSetBy = Automatic

	partition HR_Analytics = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\MaruthiYR\Downloads\HR_Analytics.csv"),[Delimiter=",", Columns=38, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EmpID", type text}, {"Age", Int64.Type}, {"AgeGroup", type text}, {"Attrition", type text}, {"BusinessTravel", type text}, {"DailyRate", Int64.Type}, {"Department", type text}, {"DistanceFromHome", Int64.Type}, {"Education", Int64.Type}, {"EducationField", type text}, {"EmployeeCount", Int64.Type}, {"EmployeeNumber", Int64.Type}, {"EnvironmentSatisfaction", Int64.Type}, {"Gender", type text}, {"HourlyRate", Int64.Type}, {"JobInvolvement", Int64.Type}, {"JobLevel", Int64.Type}, {"JobRole", type text}, {"JobSatisfaction", Int64.Type}, {"MaritalStatus", type text}, {"MonthlyIncome", Int64.Type}, {"SalarySlab", type text}, {"MonthlyRate", Int64.Type}, {"NumCompaniesWorked", Int64.Type}, {"Over18", type text}, {"OverTime", type text}, {"PercentSalaryHike", Int64.Type}, {"PerformanceRating", Int64.Type}, {"RelationshipSatisfaction", Int64.Type}, {"StandardHours", Int64.Type}, {"StockOptionLevel", Int64.Type}, {"TotalWorkingYears", Int64.Type}, {"TrainingTimesLastYear", Int64.Type}, {"WorkLifeBalance", Int64.Type}, {"YearsAtCompany", Int64.Type}, {"YearsInCurrentRole", Int64.Type}, {"YearsSinceLastPromotion", Int64.Type}, {"YearsWithCurrManager", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

